/**
 * The Next.js worker generated by `opennextjs-cloudflare build`.
 *
 * Declared rather than imported for its real types because `.open-next/` is a
 * build artefact: it doesn't exist in a fresh clone, so typechecking would fail
 * before the first build. A `@ts-expect-error` doesn't work either — it becomes
 * "unused directive" the moment the file does exist, so the repo would fail
 * typecheck in exactly one of the two states.
 */
declare module '*/.open-next/worker.js' {
  const handler: {
    fetch: (
      request: Request,
      env: CloudflareEnv,
      ctx: ExecutionContext,
    ) => Promise<Response>;
  };
  export default handler;
}
